language: node_js

node_js:
  - 0.10.31

before_install:
  - npm install -g npm@'>=2.13.5'

script:
  - npm run build

deploy:
  provider: npm
  email: esolen@yieldbot.com
  api_key: $API_KEY
  on:
    tags: true
    branch: master

#after_success:
#  - npm run copy_build_to_dist
#  - git commit . -m 'copy build files to dist (travis)'
#  - git fetch
#  - git rebase
#  - git push