language: node_js

node_js:
  - 0.10.31

before_install:
 npm install -g npm@'>=2.13.5'

script:
  - "npm run build"

deploy:
  provider: npm
  email: esolen@yieldbot.com
  api_key: $API_KEY
  on:
    tags: true
    branch: master